allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-panic-in-tests = true
allow-print-in-tests = true
allow-indexing-slicing-in-tests = true
allow-unwrap-in-tests = true

inherent-impl-lint-scope = "module"
missing-docs-in-crate-items = true
