edition = "2024"
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "Vertical"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
comment_width = 100
wrap_comments = true
